name: Checks
on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 22
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew check