name: Checks
on:
  push:
jobs:

  check:
    name: Compile and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22
      - uses: gradle/develocity-actions/maven-setup@v1
      - run: mvn verify
